### ISSUE TITLE
Problem with access not exist object

### ISSUE THREAD

**Issue by pokornyIt** [pokornyIt/finesse-agents#3]
goroutine 35 [running]:
github.com/pokornyIt/finesse-api.(*FinesseServer).readyAgentRoutineWithStatus(0x0?, {0xc00019c900, 0x4}, 0x1, 0x0?, 0xc00019d9d0)
        /home/runner/go/pkg/mod/github.com/pokorny!it/finesse-api@v0.1.0/finesse-server-parallel.go:214 +0x2b5
created by github.com/pokornyIt/finesse-api.(*FinesseServer).parallelProcessingWithState
        /home/runner/go/pkg/mod/github.com/pokorny!it/finesse-api@v0.1.0/finesse-server-parallel.go:342 +0x4ce

**Comment by pokornyIt** [comment]
Fix in version v0.2.0
